### ISSUE TITLE
Try reconnecting API for bad signature errors

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/faucet#3]
Follow-up for https://github.com/pendulum-chain/pendulum/issues/411

## Context
We saw that the faucet might get stuck with
```
2024-02-13 14:00:50        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Transaction has a bad signature
```

when using a cached `api` object after a runtime upgrade was executed on a network.

## TODO

We should keep the caching logic but add handling so that once the error is encountered, the `api` object is re-instantiated (just creating a new `api` connecting to the same network should be enough).

**Comment by ebma** [comment]
@pendulum-chain/product this ticket solves a problem where our faucet can get stuck after a runtime upgrade happened.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/faucet/3?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by prayagd** [comment]
moved to review as it has a PR linked and already been approved
